{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "ssh-service.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "ssh-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  sshd_config: >
  {{ include "ssh-service.sshd_config" . | nindent 4 }}
  user_config: >
  {{ toPrettyJson .Values.userConfig | nindent 4 }}
{{- end }}
